AHC_MLK/AHC_MLK/Controllers/Admin/BoardListController.cs
using AHCBL.Component.Common;
using AHCBL.Dao;
using AHCBL.Dao.Admin;
using AHCBL.Dto.Admin;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AHC_MLK.Controllers.Admin
{
    public class BoardListController : Controller
    {
        // GET: BoardList
        Permission checkuser = new Permission();        
        public ActionResult Index(int? page)
        {
            checkuser.chkrights("admin");
            var data = BoardListDao.Instance.GetDataList();
            string count = string.Empty;
            if (data.Count < 1000)
            {
                count = data.Count.ToString();
            }
            else
            {
                count = data.Count.ToString("0,0", CultureInfo.InvariantCulture);
            }
            ViewBag.Count = count;
            ViewBag.grp_id = DropdownDao.Instance.GetDataGroup(3);
            ViewBag.skin_id = DropdownDao.Instance.GetDataSkin("pc");
            ViewBag.skin_mobile_id = DropdownDao.Instance.GetDataSkin("mobile");
            ViewBag.device_id = DropdownDao.Instance.GetDataDrive();
            int rows = Convert.ToInt32(ConfigurationManager.AppSettings["rows"]);
            ViewBag.rows = rows;
            return View(data.ToList().ToPagedList(page ?? 1, Util.NVLInt(rows)));
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            ViewBag.grp_id = DropdownDao.Instance.GetDataGroup(3);
            ViewBag.device_id = DropdownDao.Instance.GetDataDrive();
            var No = DropdownDao.Instance.GetMemberNo();
            ViewBag.list_level = No;
            ViewBag.read_level = No;
            ViewBag.write_level = No;
            ViewBag.reply_level = No;
            ViewBag.comment_level = No;
            ViewBag.link_level = No;
            ViewBag.upload_level = No;
            ViewBag.download_level = No;
            ViewBag.html_level = No;
            ViewBag.use_secret = DropdownDao.Instance.GetUsecret();
            var config = Varible.Config;
            var use_cert = config.cert_use;
            if (use_cert != 0)
            {
                ViewBag.use_cert = DropdownDao.Instance.GetDataConfirm();
            }
            else
            {
                ViewBag.use_cert = "";
            }
            ViewBag.skin_id = DropdownDao.Instance.GetDataSkin("pc");
            ViewBag.skin_mobile_id = DropdownDao.Instance.GetDataSkin("mobile");
            ViewBag.skin = Util.NVLInt(ConfigurationManager.AppSettings["skin_id"]);
            ViewBag.skin_mobile = Util.NVLInt(ConfigurationManager.AppSettings["skin_mobile_id"]);
            ViewBag.head = Util.NVLString(ConfigurationManager.AppSettings["head"]);
            ViewBag.tail = Util.NVLString(ConfigurationManager.AppSettings["tail"]);
            ViewBag.page_rows = config.page_rows;
            ViewBag.gallery_id = DropdownDao.Instance.GetMemberNo();
            ViewBag.gallery_cols = Util.NVLInt(ConfigurationManager.AppSettings["gallery_cols"]);
            ViewBag.reply_order = DropdownDao.Instance.GetAnswer();
            ViewBag.sort_field = DropdownDao.Instance.GetSortField();
            return View();
        }

        [HttpPost]
        public ActionResult Create(BoardListDto model)
        {

            try
            {
                if (ModelState.IsValid)
                {

                    string result = BoardListDao.Instance.SaveDataList(model, "add");
                    if (result != "OK")
                    {
                        ViewBag.Message = result;
                        ModelState.Clear();
                    }
                    else
                    {
                        ViewBag.grp_id = DropdownDao.Instance.GetDataGroup(3);
                        ViewBag.device_id = DropdownDao.Instance.GetDataDrive();
                        var No = DropdownDao.Instance.GetMemberNo();
                        ViewBag.list_level = No;
                        ViewBag.read_level = No;
                        ViewBag.write_level = No;
                        ViewBag.reply_level = No;
                        ViewBag.comment_level = No;
                        ViewBag.link_level = No;
                        ViewBag.upload_level = No;
                        ViewBag.download_level = No;
                        ViewBag.html_level = No;
                        ViewBag.use_secret = DropdownDao.Instance.GetUsecret();
                        var config = Varible.Config;
                        var use_cert = config.cert_use;
                        if (use_cert != 0)
                        {
                            ViewBag.use_cert = DropdownDao.Instance.GetDataConfirm();
                        }
                        else
                        {
                            ViewBag.use_cert = "";
                        }
                        ViewBag.skin_id = DropdownDao.Instance.GetDataSkin("pc");
                        ViewBag.skin_mobile_id = DropdownDao.Instance.GetDataSkin("mobile");
                        ViewBag.skin = Util.NVLInt(ConfigurationManager.AppSettings["skin_id"]);
                        ViewBag.skin_mobile = Util.NVLInt(ConfigurationManager.AppSettings["skin_mobile_id"]);
                        ViewBag.head = Util.NVLString(ConfigurationManager.AppSettings["head"]);
                        ViewBag.tail = Util.NVLString(ConfigurationManager.AppSettings["tail"]);
                        ViewBag.page_rows = config.page_rows;
                        ViewBag.gallery_id = DropdownDao.Instance.GetMemberNo();
                        ViewBag.gallery_cols = Util.NVLInt(ConfigurationManager.AppSettings["gallery_cols"]);
                        ViewBag.reply_order = DropdownDao.Instance.GetAnswer();
                        ViewBag.sort_field = DropdownDao.Instance.GetSortField();
                        //ViewBag.Status = TempData["Dropdown"];
                        ViewBag.Message = "Successfully !!";
                        //KRPBL.Component.Common.Form.SetAlertMessage(this,"ไม่พบ User ID ที่ระบุ กรุณาตรวจสอบ");
                        ModelState.Clear();
                    }
                }
                return View();
            }
            catch (Exception e)
            {
                ViewBag.Message = "Error : " + e.Message;
                return View();
            }
        }

        // GET: ContentList/Edit/5
        public ActionResult Edit(int id)
        {
            var model = BoardListDao.Instance.GetDataList().Find(smodel => smodel.id == id);
            ViewBag.grp_id = DropdownDao.Instance.GetDataGroup(3);
            ViewBag.device_id = DropdownDao.Instance.GetDataDrive();
            var No = DropdownDao.Instance.GetMemberNo();
            ViewBag.list_level = No;
            ViewBag.read_level = No;
            ViewBag.write_level = No;
            ViewBag.reply_level = No;
            ViewBag.comment_level = No;
            ViewBag.link_level = No;
            ViewBag.upload_level = No;
            ViewBag.download_level = No;
            ViewBag.html_level = No;
            ViewBag.use_secret = DropdownDao.Instance.GetUsecret();
            var config = Varible.Config;
           
            ViewBag.use_cert = DropdownDao.Instance.GetDataConfirm();
           
            ViewBag.skin_id = DropdownDao.Instance.GetDataSkin("pc");
            ViewBag.skin_mobile_id = DropdownDao.Instance.GetDataSkin("mobile");
            ViewBag.skin = Util.NVLInt(ConfigurationManager.AppSettings["skin_id"]);
            ViewBag.skin_mobile = Util.NVLInt(ConfigurationManager.AppSettings["skin_mobile_id"]);
            ViewBag.head = Util.NVLString(ConfigurationManager.AppSettings["head"]);
            ViewBag.tail = Util.NVLString(ConfigurationManager.AppSettings["tail"]);
            ViewBag.page_rows = config.page_rows;
            ViewBag.gallery_id = DropdownDao.Instance.GetMemberNo();
            ViewBag.gallery_cols = Util.NVLInt(ConfigurationManager.AppSettings["gallery_cols"]);
            ViewBag.reply_order = DropdownDao.Instance.GetAnswer();
            ViewBag.sort_field = DropdownDao.Instance.GetSortField();
            return View(model);
        }

        // POST: ContentList/Edit/5
        [HttpPost]
        public ActionResult Edit(BoardListDto model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string result = BoardListDao.Instance.SaveDataList(model, "edit");
                    if (result != "OK")
                    {
                        ViewBag.Message = result;
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }
                    return View();

                } 
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(BoardListDto model, string[] data)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    foreach (string id in data)
                    {
                        model.id = Util.NVLInt(id);
                        BoardListDao.Instance.SaveDataList(model, "del");
                    }
                    return Json("Deleted successfully !");
                }
                else
                {
                    return Json("Data not found !");
                }
            }
            catch (Exception e)
            {
                return Json("Error");
            }


            //try
            //{
            //    string result = BoardListDao.Instance.SaveDataList(model, "del");

AHC_MLK/AHC_MLK/Controllers/Admin/CategoryListController.cs
using AHCBL.Component.Common;
using AHCBL.Dao.Admin;
using AHCBL.Dto.Admin;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AHC_MLK.Controllers.Admin
{
    public class CategoryListController : Controller
    {
        Permission checkuser = new Permission();
        // GET: CategoryList
        public ActionResult Index(int? page)
        {
            checkuser.chkrights("admin");
            var data = CategoryListDao.Instance.GetDataList();
            string count = string.Empty;
            if (data.Count < 1000)
            {
                count = data.Count.ToString();
            }
            else
            {
                count = data.Count.ToString("0,0", CultureInfo.InvariantCulture);
            }
            ViewBag.Count = count;            
            int rows = Convert.ToInt32(ConfigurationManager.AppSettings["rows"]);
            ViewBag.rows = rows;
            return View(data.ToList().ToPagedList(page ?? 1, Util.NVLInt(rows)));

        }
        public ActionResult Create(int id)
        {
            var data = CategoryListDao.Instance.GetDataList().Find(smodel => smodel.id == id);
            data.code = data.code + "10";
            return View(data);
        }


        [HttpPost]
        public ActionResult Create(CategoryListDto model)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    string result = CategoryListDao.Instance.SaveDataList(model, "add");
                    if (result != "OK")
                    {
                        ViewBag.Message = result;
                        ModelState.Clear();
                    }
                    else
                    {
                        //ViewBag.Status = TempData["Dropdown"];
                        ViewBag.Message = "Successfully !!";
                        ModelState.Clear();
                    }
                }
                return View();
            }
            catch (Exception e)
            {
                ViewBag.Message = "Error : " + e.Message;
                return View();
            }
        }
        public ActionResult Edit(int id)
        {
            var data = CategoryListDao.Instance.GetDataList().Find(smodel => smodel.id == id);
            return View(data);
        }
        [HttpPost]
        public ActionResult Edit(CategoryListDto model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string result = CategoryListDao.Instance.SaveDataList(model, "edit");
                    if (result != "OK")
                    {
                        ViewBag.Message = result;
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }
                    return View();
                }
                else
                {
                    return View();
                }
                
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Delete(CategoryListDto model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //model.id = id;
                    CategoryListDao.Instance.SaveDataList(model, "del");
                    return Json("Delete Successfully !");
                }
                else
                {
                    return Json("Data not found !");
                }
            }
            catch (Exception e)
            {
                return Json("Error");
            }
            //}
            //try
            //{
            //    string result = PopupListDao.Instance.SaveDataList(model, "del");
            //    if (result == "OK")
            //    {
            //        ViewBag.Message = "Student Deleted Successfully";
            //    }
            //    return RedirectToAction("Index");
            //}
            //catch (Exception e)
            //{
            //    ViewBag.Message = "Error : " + e.Message.ToString();
            //    return View();
            //}
        }
    }
}

AHC_MLK/AHC_MLK/Views/CategoryList/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<AHCBL.Dto.Admin.CategoryListDto>
@{
    ViewBag.Title = "Category List";
}

<div class="xp-contentbar" style="margin-top:60px;">
    <div class="row">
        <!-- Start XP Col -->
        <div class="col-md-12 col-lg-12 col-xl-12">
            <div class="card m-b-30">
                <div class="card-header bg-white">
                    <div class="float-left">
                        <h5 class="card-title text-black">분류관리 / การจัดการกระดานข่าว</h5>
                    </div>
                </div>
                <div class="col-md-12 col-lg-12 col-xl-12">
                    <div class="xp-alert mt-3">


                    </div>
                </div>
                <div class="card-body" style="margin-top:-20px;">
                    <div class="align-middle">
                        <span class="badge badge-primary badge-pill">생성된 분류 수 @ViewBag.Count 개</span>
                        @*<div class="float-right">
                                <button type="button" id="btnDel" style="margin-top:-10px;" class="btn btn-rounded btn-danger"><i class="icon-trash mr-2"></i> Delete</button>
                                <button type="button" style="margin-top:-10px;" class="btn btn-rounded btn-success" onclick="location.href='@Url.Action("Create", "BoardList")'"><i class="icon-plus mr-2"></i> Insert</button>
                            </div>*@
                    </div>
                    <div class="table-responsive m-b-30 mt-2">
                        <table class="table table-bordered">
                            <thead class="thead-dark">
                                <tr class="text-center">
                                    <th class="align-middle" style="width:60px;">분류코드 / รหัสการจำแนกประเภท</th>
                                    <th class="align-middle">분류명 / ชื่อหมวดหมู่</th>
                                    <th class="align-middle" style="width:200px;">최소금액(달러) / จำนวนเงินขั้นต่ำ (ดอลลาร์)</th>
                                    <th class="align-middle" style="width:200px;">
                                        최대금액(달러) / จำนวนเงินสูงสุด (ดอลลาร์)
                                    </th>
                                    <th class="align-middle" style="width:170px;">
                                        보유기간 / ระยะเวลาเก็บรักษา
                                    </th>
                                    <th class="align-middle" style="width:90px;">수익 / รายได้</th>
                                    <th class="align-middle" style="width:90px;">충전시간 / เวลาในการชาร์จ</th>

                                    <th class="align-middle" style="width:90px;">마블마블 / หินอ่อนหินอ่อน </th>
                                    <th class="align-middle" style="width:90px;">일최대 당첨가능수 / จำนวนเงินรางวัลสูงสุดต่อวัน</th>
                                    <th class="align-middle" style="width:200px;">일최대 당첨가능금액(달러) / จำนวนเงินที่ชนะสูงสุดต่อวัน (ดอลลาร์) </th>
                                    <th class="align-middle" style="width:100px;">
                                        상품수 / จำนวนสินค้า
                                    </th>
                                    <th class="align-middle" style="width:150px;">
                                        관리 / การจัดการ
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model.Count() != 0)
                                {
                                    foreach (var item in Model)
                                    {
                                        <tr class="text-center">
                                            <td> @Html.DisplayFor(modelItem => item.code)</td>
                                            <td> @Html.EditorFor(modelItem => item.name, new { htmlAttributes = new { @class = "form-control bg-white border" } })</td>
                                            <td> @Html.EditorFor(modelItem => item.min_price, new { htmlAttributes = new { @class = "form-control bg-white border" } })</td>
                                            <td> @Html.EditorFor(modelItem => item.max_price, new { htmlAttributes = new { @class = "form-control bg-white border" } }) </td>
                                            <td> @Html.EditorFor(modelItem => item.day, new { htmlAttributes = new { @class = "form-control bg-white border" } }) </td>
                                            <td> @Html.EditorFor(modelItem => item.revenue, new { htmlAttributes = new { @class = "form-control bg-white border" } })</td>
                                            <td> @Html.EditorFor(modelItem => item.charging_time, new { htmlAttributes = new { @class = "form-control bg-white border" } })</td>
                                            <td> @Html.EditorFor(modelItem => item.energy, new { htmlAttributes = new { @class = "form-control bg-white border" } })</td>
                                            <td> @Html.EditorFor(modelItem => item.win_count, new { htmlAttributes = new { @class = "form-control bg-white border" } })</td>
                                            <td> @Html.EditorFor(modelItem => item.win_max_price, new { htmlAttributes = new { @class = "form-control bg-white border" } })</td>
                                            <td> @Html.DisplayFor(modelItem => item.product_amt)</td>
                                            <td>
                                                <div class="justify-content-center row">
                                                    @using (Html.BeginForm("Create", "CategoryList", new { id = item.id }, FormMethod.Get))
                                                    {
                                                        <button type="submit" class="btn btn-round btn-success" style="float: none; margin: 5px;" title="추가">
                                                            <span class="icon-plus"></span>
                                                        </button>
                                                    }

                                                    @using (Html.BeginForm("Edit", "CategoryList", new { id = item.id }, FormMethod.Get))
                                                    {
                                                        <button type="submit" class="btn btn-round btn-primary" style="float: none; margin: 5px;" title="삭제">
                                                            <span class="icon-note"></span>
                                                        </button>
                                                    }
                                                    <button type="button" onclick="Del('@Html.DisplayFor(modelItem => item.id)');" class="btn btn-round btn-danger" style="float: none; margin: 5px;" title="수정">
                                                        <span class="icon-trash"></span>
                                                    </button>
                                                </div>
                                            </td>
                                        </tr>

                                    }
                                }
                                else
                                {
                                    <tr class="text-center">
                                        <td colspan="13">
                                            No Data !!
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        @{
                            if (Convert.ToInt32(ViewBag.Count) > ViewBag.rows)
                            {
                                <div class="justify-content-center row">

                                    @Html.PagedListPager(Model, Page => Url.Action("Index", "CategoryList", new { Page }))

                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $("#liCategory").addClass("active");
        $("#meCategory").addClass("active");
    });
    function Del(id) {
        var r = confirm("1구좌 추가생성하시겠습니까??");
        if (r == true) {
            $.ajax({
                type: "POST",
                url: "/CategoryList/Delete",
                data: "{'id':'" + id + "'}",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (msg) {
                    alert(msg);
                    location.reload();
                }
            });
        }
    }
</script>