AHC_MLK/AHC_MLK/Controllers/Admin/ConfigController.cs
using AHCBL.Component.Common;
using AHCBL.Dao;
using AHCBL.Dao.Admin;
using AHCBL.Dto.Admin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AHC_MLK.Controllers.Admin
{
    public class ConfigController : Controller
    {
        Permission checkuser = new Permission();
        // GET: Config
        //public ActionResult Index()
        //{
        //    TempData["Skin"] = DropdownDao.Instance.GetSkin();
        //    ViewBag.member_id_list = new SelectList(Skin, "Value", "Text");
        //    ViewBag.new_skin = TempData["Skin"];
        //    ViewBag.mobile_new_skin = TempData["Skin"];
        //    ViewBag.search_skin = TempData["Skin"];
        //    ViewBag.mobile_search_skin = TempData["Skin"];
        //    ViewBag.connect_skin = TempData["Skin"];
        //    ViewBag.mobile_connect_skin = TempData["Skin"];
        //    ViewBag.faq_skin = TempData["Skin"];
        //    ViewBag.mobile_faq_skin = TempData["Skin"];
        //    ViewBag.member_id = DropdownDao.Instance.GetDataAdmin();
        //    //return View(ConfigDao.Instance.GetDataList().Find(smodel => smodel.id == 1));

        //    ViewBag.captcha = DropdownDao.Instance.GetDataCaptcha();

        //    ViewBag.link_target = DropdownDao.Instance.GetLink();
        //    ViewBag.member_skin = TempData["Skin"];
        //    ViewBag.mobile_member_skin = TempData["Skin"];
        //    TempData["level"] = DropdownDao.Instance.GetMemberLevel();
        //    ViewBag.register_level = TempData["level"];
        //    ViewBag.icon_level = TempData["level"];
        //    ViewBag.use_member_icon = DropdownDao.Instance.GetMemberIcon();
        //    ViewBag.cert_use = DropdownDao.Instance.GetIdCard();
        //    ViewBag.sms_use = DropdownDao.Instance.GetSMS();
        //    ViewBag.sms_type = DropdownDao.Instance.GetSMSType();
        //    return View(ConfigDao.Instance.GetDataList());
        //}

        public ActionResult Index()
        {
            checkuser.chkrights("admin");
            int id = 1;
            var Skin = DropdownDao.Instance.GetSkin();
            var cert_use = DropdownDao.Instance.GetIdCard();
            //ViewBag.member_id = TempData["Skin"];

            var model = ConfigDao.Instance.GetDataList().Find(smodel => smodel.id == id);
            var adm = DropdownDao.Instance.GetDataAdmin();
            model.member_id_list = new SelectList(adm, "Value", "Text");
            model.exchange = Util.NVLString(model.exchange).Replace(".00","");
            model.jewel_price = Util.NVLString(model.jewel_price).Replace(".00", "");
            model.day_max = Util.NVLString(model.day_max).Replace(".00", "");

            model.cert_use_list = new SelectList(cert_use, "Value", "Text");


            model.new_skin_list = new SelectList(Skin, "Value", "Text");
            model.mobile_new_skin_list = new SelectList(Skin, "Value", "Text");
            model.search_skin_list = new SelectList(Skin, "Value", "Text");
            model.mobile_search_skin_list = new SelectList(Skin, "Value", "Text");
            model.connect_skin_list = new SelectList(Skin, "Value", "Text");
            model.mobile_connect_skin_list = new SelectList(Skin, "Value", "Text");
            model.faq_skin_list = new SelectList(Skin, "Value", "Text");
            model.mobile_faq_skin_list = new SelectList(Skin, "Value", "Text");
            var captcha = DropdownDao.Instance.GetDataCaptcha();
            model.captcha_list = new SelectList(captcha, "Value", "Text");
            var link_target = DropdownDao.Instance.GetLink();
            model.link_target_list = new SelectList(link_target, "Value", "Text");
            model.member_skin_list = new SelectList(Skin, "Value", "Text");
            model.mobile_member_skin_list = new SelectList(Skin, "Value", "Text");

            var level = DropdownDao.Instance.GetMemberLevel();
            model.register_level_list = new SelectList(level, "Value", "Text");
            model.icon_level_list = new SelectList(level, "Value", "Text");


            var use_member_icon = DropdownDao.Instance.GetMemberIcon();
            model.use_member_icon_list = new SelectList(use_member_icon, "Value", "Text");

            var sms_use = DropdownDao.Instance.GetSMS();
            model.sms_use_list = new SelectList(sms_use, "Value", "Text");

            var sms_type = DropdownDao.Instance.GetSMSType();
            model.sms_type_list = new SelectList(sms_type, "Value", "Text");

            var cert_ipin = DropdownDao.Instance.GetIPIN();
            model.cert_ipin_list = new SelectList(cert_ipin, "Value", "Text");
            var cert_hp = DropdownDao.Instance.GetCertHP();
            model.cert_hp_list = new SelectList(cert_hp, "Value", "Text");

            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(ConfigDto model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string result = ConfigDao.Instance.SaveDataList(model);
                    if (result != "OK")
                    {
                        ViewBag.Message = result;
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }
                    return View();
                }
                else
                {
                    return View();
                }
                
            }
            catch
            {
                return View();
            }
        }
    }
}

AHC_MLK/AHC_MLK/Controllers/Admin/QAConfigController.cs
using AHCBL.Component.Common;
using AHCBL.Dao;
using AHCBL.Dao.Admin;
using AHCBL.Dto.Admin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AHC_MLK.Controllers.Admin
{
    public class QAConfigController : Controller
    {
        Permission checkuser = new Permission();
        // GET: QAConfig
        public ActionResult Index()
        {
            checkuser.chkrights("admin");
            var Skin = DropdownDao.Instance.GetSkin();
            var noti = DropdownDao.Instance.GetNoTi();
            
            var model = QAConfigDao.Instance.GetDataList().Find(smodel => smodel.id == 1);

            model.skin_list = new SelectList(Skin, "Value", "Text");
            model.mobile_skin_list = new SelectList(Skin, "Value", "Text");

            model.use_sms_list = new SelectList(noti, "Value", "Text");
            model.use_editor_list = new SelectList(noti, "Value", "Text");

            return View(model);
        }
       

        [HttpPost]
        public ActionResult Index(QAConfigDto model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string result = QAConfigDao.Instance.SaveDataList(model);
                    if (result != "OK")
                    {
                        ViewBag.Message = result;
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    ViewBag.Message = "Data not found !";
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

    }
}

AHC_MLK/AHC_MLK/Views/QAConfig/Index_bk.cshtml
@model AHCBL.Dto.Admin.QAConfigDto
@{
    ViewBag.Title = "QA Config";
}

@using (Html.BeginForm("Edit", "Config", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <input type="submit" value="Save" class="btn btn-default btn-fixed-top" />
    <div class="xp-contentbar" style="margin-top:60px;">
        <div class="row">
            <!-- Start XP Col -->
            <div class="col-md-12 col-lg-12 col-xl-12">
                <div class="card m-b-30">
                    <div class="card-header bg-white">
                        <h5 class="card-title text-black">1:1문의 설정</h5>
                    </div>
                    <div class="card-body">
                        <div class="alert alert-light" role="alert">
                            <p>
                                메일 내용에 {이름} , {닉네임} , {회원아이디} , {이메일} 처럼 내용에 삽입하면 해당 내용에 맞게 변환하여 메일을 발송합니다.
                            </p>
                        </div>
                        <div class="table-responsive">
                            <div style="min-width:1366px;max-width:100%; margin:auto;">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.id)
                                <table class="table">
                                    <tr>
                                        <th>
                                            <label>메일 제목필수</label>
                                        </th>
                                        <td>
                                            @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control bg-white border" } })
                                            @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            <label>메일 내용필수</label>
                                        </th>
                                        <td>
                                        </td>
                                    </tr>
                                    <tr><td colspan="2"></td></tr>
                                </table>
                                <div class="form-group text-center">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="button" value="Back" onclick="location.href='@Url.Action("Index", "SendEmail")'" class="btn btn-light" />
                                        <input type="submit" value="Save" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}











@*@model IEnumerable<AHCBL.Dto.Admin.QAConfigDto>
    @{
        ViewBag.Title = "QA Config";
    }
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.directory_skin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mobile_directory_skin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.use_email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mobile_use_email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.use_sms)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.send_number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mobile_admin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.email_admin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.use_editor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.subject_len)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mobile_subject_len)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.page_rows)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mobile_page_rows)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.image_width)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.upload_size)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.include_top)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.include_bottom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.detail_hots)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.detail_bottom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mobile_detail_hots)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mobile_detail_bottom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.insert_content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.subj1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.subj2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.subj3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.subj4)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.subj5)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.txt1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.txt2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.txt3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.txt4)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.txt5)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.directory_skin)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.mobile_directory_skin)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.use_email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.mobile_use_email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.use_sms)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.send_number)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.mobile_admin)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.email_admin)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.use_editor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.subject_len)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.mobile_subject_len)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.page_rows)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.mobile_page_rows)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.image_width)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.upload_size)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.include_top)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.include_bottom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.detail_hots)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.detail_bottom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.mobile_detail_hots)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.mobile_detail_bottom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.insert_content)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.subj1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.subj2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.subj3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.subj4)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.subj5)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.txt1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.txt2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.txt3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.txt4)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.txt5)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.id })
                </td>
            </tr>
        }

    </table>*@