AHC_MLK/AHC_MLK/Controllers/User/MainController.cs
using AHCBL.Component.Common;
using AHCBL.Dao;
using AHCBL.Dao.Admin;
using AHCBL.Dao.User;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AHC_MLK.Controllers.User
{
    public class MainController : Controller
    {
        Permission checkuser = new Permission();
        // GET: main
        public ActionResult Index()
        {
            checkuser.chkrights("user");
            ViewBag.amount = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);
            var pm = GetDataDao.Instance.GetProductMember();
            ViewBag.PM = pm;


            int rows = Util.NVLInt(ConfigurationManager.AppSettings["rows"]);
            var data = OrderDao.Instance.GetOrderHis();
            ViewBag.his_tb = data;
            ViewBag.cnt = data.Count();

            //var dataNotice = NoticeDao.Instance.GetDataQA();
            //ViewBag.dataNotice = dataNotice;
            //ViewBag.cntNotice = dataNotice.Count();
            int? page = null;
            var dataNotice = ContentListDao.Instance.GetDataList();
            ViewBag.dataNotice = dataNotice.ToList().ToPagedList(page ?? 1, Util.NVLInt(ConfigurationManager.AppSettings["rows"]));
            ViewBag.cntNotice = dataNotice.Count();

            return View();
        }
    }
}

AHC_MLK/AHC_MLK/Controllers/User/MemberController.cs
using AHCBL.Component.Common;
using AHCBL.Dao;
using AHCBL.Dao.Admin;
using AHCBL.Dao.User;
using AHCBL.Dto;
using AHCBL.Dto.Admin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AHC_MLK.Controllers.User
{
    public class MemberController : Controller
    {
        Permission checkuser = new Permission();
        // GET: Member
        public ActionResult Index()
        {
            if (ModelState.IsValid)
            {
                checkuser.chkrights("user");
                //ViewBag.Bank = DropdownDao.Instance.GetDataBank();
                ViewBag.OldPass = Varible.User.pass;
                var model = MemberListDao.Instance.GetDataList().Find(smodel => smodel.id == Varible.User.member_id);
                var bank_id = DropdownDao.Instance.GetDataBank();
                model.bank_list = new SelectList(bank_id, "Value", "Text");


                return View(model);
            } 
            else
            {
                return View();
            }
                
        }
        public ActionResult ChangeBank(int id,int bank_id,string acc_no,string acc_name)
        {
            try
            {

                MemberListDto model = new MemberListDto();
                model.id = id;
                model.bank_id = bank_id;
                model.acc_no = acc_no;
                model.acc_name = acc_name;

                string result = MemberDao.Instance.ChangeBank(model);
                if (result != "OK")
                {
                    //ViewBag.Message = result;
                    return Json(new returnsave { err = "1", errmsg = result });
                }
                else
                {
                    //return RedirectToAction("Member");
                    return Json(new returnsave { err = "0", errmsg = "Successfully !" });
                }

            }
            catch (Exception e)
            {
                return Json(new returnsave { err = "0", errmsg = "Error" });
            }


            //return objreturnsave;
        }
        //[HttpPost]
        //public ActionResult ChangeBank(MemberListDto model)
        //{
        //    try
        //    {

        //        string result = MemberDao.Instance.ChangeBank(model);
        //        if (result != "OK")
        //        {
        //            ViewBag.Message = result;
        //        }
        //        else
        //        {
        //            //return RedirectToAction("Member");
        //            return View("Member");
        //        }
        //        return View();


        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}



        public ActionResult ChangePass(int id ,string pass)
        {
            try
            {
                MemberDao.Instance.ChangePass(id,pass);
                return Json("Successfully !");
            }
            catch (Exception e)
            {
                return Json("Error");
            }
        }


        //[HttpPost]
        //public ActionResult ChangePass(MemberListDto model)
        //{
        //    try
        //    {
        //        if (Varible.User.pass != model.password)
        //        {
        //            return Json(new { status = "Error", message = "Password incorrect !" });
        //        }
        //        //string result = MemberDao.Instance.ChangeBank(model);
        //        //if (result != "OK")
        //        //{
        //        //    ViewBag.Message = result;
        //        //}
        //        //else
        //        //{
        //        //    return RedirectToAction("Index");
        //        //}
        //        return View();
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

    }
}

AHC_MLK/AHC_MLK/Controllers/User/NoticeController.cs
using AHCBL.Component.Common;
using AHCBL.Dao.Admin;
using AHCBL.Dao.User;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AHC_MLK.Controllers.User
{
    public class NoticeController : Controller
    {
         Permission checkuser = new Permission();
        // GET: Notice
        public ActionResult Index(int? page)
        {
            checkuser.chkrights("user");
            var data = ContentListDao.Instance.GetDataList();
            return View(data.ToList().ToPagedList(page ?? 1, Util.NVLInt(ConfigurationManager.AppSettings["rows"])));
        }
        //public ActionResult Notice_detail(int? page)
        //{
        //    //var data = ContentListDao.Instance.GetDataList();
        //    //return View(data.ToList().ToPagedList(page ?? 1, Util.NVLInt(ConfigurationManager.AppSettings["rows"])));
        //    return View();
        //}
        public ActionResult Notice_detail(int? id)
        {
            checkuser.chkrights("user");
            var data = ContentListDao.Instance.GetDataList().Find(smodel => smodel.id == id);
            return View(data);
        }
        public ActionResult qna(int? page)
        {
            checkuser.chkrights("user");
            var data = NoticeDao.Instance.GetDataQA();
            return View(data.ToList().ToPagedList(page ?? 1, Util.NVLInt(ConfigurationManager.AppSettings["rows"])));
        }
        public ActionResult qna_detail(int id)
        {
            checkuser.chkrights("user");
            var data = NoticeDao.Instance.GetDataQA().Find(smodel => smodel.id == id);
            ViewBag.comment = data.comment;
            return View(data);
        }
        
        public ActionResult qna_write()
        {
            checkuser.chkrights("user");
            return View();
        }
        [HttpPost]
        public ActionResult qna_write(string content)
        {
            try
            {
                string result= NoticeDao.Instance.SaveData(content);
                if (result!="OK")
                {
                    return Json("Error");
                }
                else
                {
                    return Json("1:1 문의가 정상적으로 등록 되었습니다.");
                }
            }
            catch (Exception e)
            {
                return Json("Error");
            }
        }

    }
}

AHC_MLK/AHC_MLK/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @*<meta charset="utf-8" />*@
    <meta http-equiv=Content-Type content="text/html; charset=tis-620">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Administrator</title>
    <link rel="icon" href="/vendor/images/logo.ico" type="image/x-icon" sizes="16x16">
    @*<script src='https://kit.fontawesome.com/a076d05399.js'></script>*@
    @*@Styles.Render("~/Content/style.css")
        @Styles.Render("~/Content/main.css")
        @Scripts.Render("~/bundles/modernizr")*@

    @Styles.Render("~/Content/css")



    <script src="~/vendor/assets/ckeditor/ckeditor.js"></script>
    <script src="~/vendor/assets/ckeditor/adapters/jquery.js"></script>
    <script src="~/vendor/Scripts/jquery/jquery.js"></script>
    <script src="~/vendor/assets/js/jquery-ui.js"></script>
    @*<script src="~/vendor/assets/js/bootstrap-datepicker.js"></script>
        <script src="~/vendor/assets/js/bootstrap-datepicker.min.js"></script>*@



    <script src="~/vendor/assets/js/postcode.v2.js"></script>



    <!-- Datepicker JS -->
    @*<script src="~/vendor/assets/js/datepicker.min.js "></script>
        <script src="~/vendor/assets/js/datepicker.en.js"></script>*@
</head>
<body class="xp-vertical">
    <div class="modal search-modal fade" id="xpSearchModal" tabindex="-1" role="dialog" aria-labelledby="xpSearchModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="xp-searchbar">
                        <form>
                            <div class="input-group">
                                <input type="search" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="button-addon2">
                                <div class="input-group-append">
                                    <button class="btn" type="submit" id="button-addon2">GO</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Start XP Container -->
    <div id="xp-container">

        <!-- Start XP Leftbar -->
        <div class="xp-leftbar">

            <!-- Start XP Sidebar -->
            <div class="xp-sidebar">

                <!-- Start XP Logobar -->
                <div class="xp-logobar text-center">
                    <a href="#" class="xp-logo">
                        <!--img src="./Neon - Bootstrap + Laravel + PHP Admin Dashboard Template_files/logo.svg" class="img-fluid" alt="logo">-->
                        AHC
                    </a>
                </div>
                <!-- End XP Logobar -->
                <!-- Start XP Navigationbar -->
                <div class="xp-navigationbar active">
                    <ul class="xp-vertical-menu in">
                        <li class="xp-vertical-header">Main</li>
                        <li  id="liDashboard">
                            <a href="~/Dashboard">
                                <i class="icon-speedometer"></i><span>Dashboard</span>
                            </a>
                        </li>
                        <li id="liConfig">
                            <a href="javaScript:void();">
                                <i class="icon-layers"></i><span>환경설정 / กำหนดค่า</span><i class="icon-arrow-right pull-right"></i>
                            </a>
                            <ul class="xp-vertical-submenu">
                                <li id="meConfig"><a href="~/Config">기본환경설정/การตั้งค่าสภาพแวดล้อมพื้นฐาน</a></li>
                                <li id="mePopup"><a href="~/PopupList">팝업레이어관리/การจัดการเลเยอร์ป๊อปอัป</a></li>
                            </ul>
                        </li>
                        <li id="liMember">
                            <a href="javaScript:void();">
                                <i class="icon-social-dropbox"></i><span>회원관리 / จัดการสมาชิก</span><i class="icon-arrow-right pull-right"></i>
                            </a>
                            <ul class="xp-vertical-submenu">
                                <li id="meMember"><a href="~/MemberList">회원관리/การจัดการสมาชิก</a></li>
                                <li id="meSendEmail"><a href="~/SendEmail">회원메일발송/ส่งอีเมลสมาชิก</a></li>
                                <li id="meVisit"><a href="~/VisitList">접속자집계/จำนวนผู้เข้าชม</a></li>
                                <li id="meVisitSearch"><a href="~/VisitList/Search">접속자검색/การค้นหาผู้เยี่ยมชม</a></li>
                                <li id="meVisitDelete"><a href="~/VisitList/Delete">접속자로그삭제/ลบบันทึกผู้เยี่ยมชม</a></li>
                                <li id="meRequest"><a href="~/RequestList">구매신청리스트/ซื้อรายการใบสมัคร</a></li>
                                <li id="meWithdrawal"><a href="~/WithdrawalList">출금신청리스트/ถอนรายการใบสมัคร</a></li>
                                <li id="mePoint"><a href="~/PointList">마블마블관리/การจัดการหินอ่อนหินอ่อน</a></li>
                                <li id="meMoney"><a href="~/MoneyList">충전하기/การเติมเงิน</a></li>
                            </ul>
                        </li>
                        <li id="liBoard">
                            <a href="javaScript:void();">
                                <i class="icon-drop"></i><span>게시판관리 / การจัดการกระดานข่าว</span><i class="icon-arrow-right pull-right"></i>
                            </a>
                            <ul class="xp-vertical-submenu">
                                <li id="meBoard"><a href="~/BoardList">게시판관리/การจัดการกระดานข่าว</a></li>
                                <li id="meQAConfig"><a href="~/QAConfig">1:1문의설정/การตั้งค่าการสอบถาม 1: 1</a></li>
                                <li id="meContent"><a href="~/ContentList">내용관리/การจัดการเนื้อหา</a></li>
                                <li id="meFAQ"><a href="~/FAQ">FAQ관리/การจัดการคำถามที่พบบ่อย</a></li>
                            </ul>
                        </li>

                        <li id="liCategory">
                            <a href="javaScript:void();">
                                <i class="icon-list"></i><span>관리 / การจัดการ</span><i class="icon-arrow-right pull-right"></i>
                            </a>
                            <ul class="xp-vertical-submenu">
                                <li id="meCategory"><a href="~/CategoryList">관리/การจัดการ</a></li>
                                <li id="meItem"><a href="~/ItemList">분류관리/การจัดการผลิตภัณฑ์</a></li>
                                <li id="meWin"><a href="~/Board?winers">상품관리/รายการที่ชนะ</a></li>
                                <li id="meReport"><a href="~/Board?report">당첨리스트/รายการรายงาน</a></li>
                                <li id="meApp"><a href="~/Board">신고리스트/รายการแอปพลิเคชัน</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- End XP Navigationbar -->

            </div>
            <!-- End XP Sidebar -->

        </div>
        <!-- End XP Leftbar -->
        <!-- Start XP Rightbar -->
        <div class="xp-rightbar">

            <!-- Start XP Topbar -->
            <div class="xp-topbar">

                <!-- Start XP Row -->
                <div class="row">

                    <!-- Start XP Col -->
                    <div class="col-2 col-md-1 col-lg-1 order-2 order-md-1 align-self-center">
                        <div class="xp-menubar">
                            <a class="xp-menu-hamburger" href="javascript:void();">
                                <i class="icon-menu font-20 text-white"></i>
                            </a>
                        </div>
                    </div>
                    <!-- End XP Col -->
                    <!-- Start XP Col -->
                    <div class="col-10 col-md-11 col-lg-11 order-1 order-md-2">
                        <div class="xp-profilebar text-right">
                            <ul class="list-inline mb-0">

                                <li class="list-inline-item mr-0">
                                    <div class="dropdown xp-userprofile">
                                        <a class="dropdown-toggle" href="https://themesbox.in/admin-templates/neon/html/vertical/index.html#" role="button" id="xp-userprofile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="~/vendor/images/profile/user.jpg" alt="user-profile" class="rounded-circle img-fluid"><span class="xp-user-live"></span></a>

                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="xp-userprofile">
                                            <a class="dropdown-item py-3 text-white text-center font-16" href="#">Welcome, @Session["username"]</a>
                                            <a class="dropdown-item" href="#"><i class="icon-user text-primary mr-2"></i> Profile</a>
                                            <a class="dropdown-item" href="#"><i class="icon-wallet text-success mr-2"></i> Billing</a>
                                            <a class="dropdown-item" href="#"><i class="icon-settings text-warning mr-2"></i> Setting</a>
                                            <a class="dropdown-item" href="#"><i class="icon-lock text-info mr-2"></i> Lock Screen</a>
                                            <a class="dropdown-item" href="/Login/LogOut"><i class="icon-power text-danger mr-2"></i> Logout</a>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- End XP Col -->

                </div>
                <!-- End XP Row -->

            </div>
            <!-- End XP Topbar -->
            <!-- Start XP Breadcrumbbar -->
            @RenderBody()

            <div class="xp-footerbar">
                <footer class="footer">
                    @*<p class="mb-0">© 2020 Neon - All Rights Reserved.</p>*@
                    <p style="margin-left:5px;">&copy; @DateTime.Now.Year - Asia Holding (AHC) Co. Ltd</p>
                </footer>
            </div>
            <!-- End XP Footerbar -->

        </div>
        <!-- End XP Rightbar -->

    </div>
    <a id="back-to-top" href="#" class="back-to-top btn btn-lg btn-outline-danger" role="button"><i class="icon-arrow-up"></i></a>
    <!-- End XP Container -->
    @*@Scripts.Render("~/bundles/jquery")*@
    @*<script>
            $("ul li").addClass("page-item");
            $("ul").addClass("page-item");
        </script>*@
    <!-- Start JS -->
    @*<script src="~/vendor/assets/js/jquery.min.js "></script>*@

    <script src="~/vendor/assets/js/popper.min.js "></script>
    <script src="~/vendor/assets/js/bootstrap.min.js "></script>
    <script src="~/vendor/assets/js/modernizr.min.js "></script>
    @*<script src="~/vendor/assets/js/detect.js "></script>*@
    <script src="~/vendor/assets/js/jquery.slimscroll.js "></script>
    <script src="~/vendor/assets/js/sidebar-menu.js "></script>






    <!-- Chartist Chart JS -->
    <!--<script src="~/vendor/assets/js/chartist.min.js "></script>
    <script src="~/vendor/assets/js/chartist-plugin-tooltip.min.js "></script>-->
    <!-- To Do List JS -->
    <!--<script src="~/vendor/assets/js/to-do-list-init.js "></script>-->
    <!-- Dashboard JS -->
    <!--<script src="~/vendor/assets/js/dashborad.js "></script>-->
    <!-- Main JS -->
    <script src="~/vendor/assets/js/main.js "></script>
    <!-- End JS -->

    <script>
        $(document).ready(function () {
            $(window).scroll(function () {
                if ($(this).scrollTop() > 50) {
                    $('#back-to-top').fadeIn();
                } else {
                    $('#back-to-top').fadeOut();
                }
            });
            // scroll body to 0px on click
            $('#back-to-top').click(function () {
                $('body,html').animate({
                    scrollTop: 0
                }, 400);
                return false;
            });

            $(".pagination li").addClass("page-item");
            $(".pagination li a").addClass("page-link");
        });
    </script>
</body>
</html>

AHC_MLK/AHC_MLK/Views/Shared/_Layout_Error.cshtml
<!DOCTYPE html>
<html>
<head>
    @*<meta charset="utf-8" />*@
    <meta http-equiv=Content-Type content="text/html; charset=tis-620">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 장미나라</title>
    <link rel="icon" href="/vendor/images/logo.ico" type="image/x-icon" sizes="16x16">
    @Styles.Render("~/Content/css")
</head>
<body class="xp-vertical">

    <div class="xp-authenticate-bg"></div>
    <!-- Start XP Container -->
    <div id="xp-container" class="xp-container">
        @RenderBody()
    </div>
    <!-- End XP Container -->
</body>
</html>

AHC_MLK/AHC_MLK/Views/Shared/_Layout_Main.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BrandName</title>
    <link rel="icon" href="../../common/image/logo.ico" type="image/gif" sizes="16x16">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    @Styles.Render("~/common/css/pages/app.css")
    @Styles.Render("~/common/css/pages/footer.css")
    @Styles.Render("~/common/css/pages/main.css")
    @Styles.Render("~/common/css/pages/login.css")
    @Styles.Render("~/common/css/pages/order_point.css")

    @Scripts.Render("~/common/js/jquery-3.4.1.min.js")
</head>
<body class="dark">
    <div class="main">
        <section class="User_info_box">
            <div class="Myinfo_box">
                <ul class="list-unstyled Myinfo_link">
                    <li class="user_id">
                    <li class="user_mail"><a href="@Url.Action("Index","Main")" class=""><i class="fa fa-home"></i><span>홈</span></a></li>
                    <li class="user_mail"><a href="@Url.Action("Index","Member")"><i class="fa fa-male"></i><span>test1</span></a></li>
                    <li class="user_mail"><a href="@Url.Action("Index","Notice")"><i class="icon-bell"></i><span>공지</span></a></li>
                    <li class="user_mail"><a class="copy" style="cursor: pointer;"><i class="icon-comment"></i><span>추천링크</span></a></li>
                    <li class="user_mail"><a href="/Login/LogOut"><i class="icon-off"></i><span>로그아웃</span></a></li>
                </ul>
            </div>
        </section>
        <section class="middle">
            <div class="content_wrap">
                <div id="google_translate_element"></div>

                @RenderBody()
            </div>
            <input type="text" value="@Session["Register"]" class="urlJoin" style="position:absolute;left:-1000px;top:-1000px;" />
        </section>
        <!--#include file="../common/footer.asp"-->
    </div>
    <!-- End of Main Content -->
    <!--JS Main-->
    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement({ pageLanguage: 'ko' }, 'google_translate_element');
        }
        //Copy Link To Friend
        document.querySelector(".copy").addEventListener("click", copyText);
        function copyText() {
            var copyText = document.querySelector(".urlJoin");
            copyText.select();
            copyText.setSelectionRange(0, 99999);
            document.execCommand("copy");
            alert("복사 된 텍스트 : " + copyText.value);
        }
    </script>
    <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
    @Scripts.Render("~/common/js/Chart.min.js")
    @Scripts.Render("~/common/js/all.js")
    @Scripts.Render("~/common/js/jquery.custom.extend.js")
    @Scripts.Render("~/common/js/commonutil.js")
    @Scripts.Render("~/common/js/jquery.cookie.js")
    @Scripts.Render("~/common/js/clipboard.min.js")
    @RenderSection("scripts", required: false)
</body>
</html>

AHC_MLK/AHC_MLK/Views/Shared/_Layout_login.cshtml
<!DOCTYPE html>
<html lang=ko>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--#include file="../common/header.asp"-->
    <title>@ViewBag.Title - 장미나라</title>
    <link rel="icon" href="../../common/image/logo.ico" type="image/gif" sizes="16x16">
    @Styles.Render("~/common/css/reset.min.css")
    @Styles.Render("~/common/css/pages/gnb.css")
    @Styles.Render("~/common/css/pages/footer.css")
    @Styles.Render("~/common/css/main.css")

    @Styles.Render("~/common/css/reset-1.css")
    @Styles.Render("~/common/css/pages/style.css")


    @Scripts.Render("~/common/js/jquery-3.4.1.min.js")
    @Scripts.Render("~/common/js/jquery.custom.extend.js")
    @Scripts.Render("~/common/js/commonutil.js")
    @Scripts.Render("~/common/js/jquery.cookie.js")
    @Scripts.Render("~/common/js/clipboard.min.js")

    <link rel="stylesheet" href="/common/css/pages/login.css?ver1">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
</head>
<body style="background-image:url('../../common/image/bg-login.png')">

    @RenderBody()
    @Scripts.Render("~/common/js/Chart.min.js")
    @Scripts.Render("~/common/js/all.js")
    @Scripts.Render("~/common/js/jquery.custom.extend.js")
    @Scripts.Render("~/common/js/commonutil.js")
    @Scripts.Render("~/common/js/jquery.cookie.js")
    @Scripts.Render("~/common/js/clipboard.min.js")
    @RenderSection("scripts", required: false)
</body>
</html>

AHC_MLK/AHC_MLK/Views/Shared/_Layout_none.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>@ViewBag.Title - 장미나라</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }

        #chart {
            width: 900px;
            height: 500px;
        }

            #chart div {
                width: 100px;
            }

            #chart img {
                height: 90px;
                width: 90px;
            }
    </style>
</head>
<body>
    @RenderBody()
</body>
</html>

AHC_MLK/AHC_MLK/Views/Shared/_Layout_regis.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 장미나라</title>
    <link rel="icon" href="../../common/image/logo.ico" type="image/gif" sizes="16x16">
    @Styles.Render("~/common/css/reset.min.css")
    @Styles.Render("~/common/css/pages/gnb.css")
    @Styles.Render("~/common/css/pages/footer.css")
    @Styles.Render("~/common/css/main.css")

    @Styles.Render("~/common/css/reset-1.css")
    @Styles.Render("~/common/css/pages/style.css")


    @Scripts.Render("~/common/js/jquery-3.4.1.min.js")
    @Scripts.Render("~/common/js/jquery.custom.extend.js")
    @Scripts.Render("~/common/js/commonutil.js")
    @Scripts.Render("~/common/js/jquery.cookie.js")
    @Scripts.Render("~/common/js/clipboard.min.js")
</head>
<Body>
    <div id="wrap" style="background-image:url('../../common/image/bg-login.png');     background-size: cover;    background-position: center;">
        <div class="container">
            <div class="dash-profile">
            </div>

            @RenderBody()
        </div>
    </div>
    <!-- End of Main Content -->
    <!--JS Main-->
    @Scripts.Render("~/common/js/Chart.min.js")
    @Scripts.Render("~/common/js/all.js")
    @Scripts.Render("~/common/js/jquery.custom.extend.js")
    @Scripts.Render("~/common/js/commonutil.js")
    @Scripts.Render("~/common/js/jquery.cookie.js")
    @Scripts.Render("~/common/js/clipboard.min.js")
    @RenderSection("scripts", required: false)
</Body>
</html>